data:
  name: titanic
  path: data

model:
  n_estimators: 100
  criterion: "gini"
  min_samples_split: 2
  min_samples_leaf: 1
  min_weight_fraction_leaf: 0.0
  max_features: "sqrt"
  min_impurity_decrease: 0.0
  bootstrap: True
  oob_score: False
  verbose: 0
  warm_start: False
  ccp_alpha: 0.0
